spring.application.name=MaisonBackend

//postgres database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/maison_db
spring.datasource.username=postgres
spring.datasource.password=yeezyszn
spring.datasource.driver-class-name=org.postgresql.Driver

