spring.application.name=MaisonBackend

spring.config.import=optional:file:.env[.properties]

//postgres database connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/maison_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

//SPRING JPA CONFIGURATION
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true    

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

paystack.secret-key=${PAYSTACK_SECRET_KEY:}
paystack.base-url=${PAYSTACK_BASE_URL:https://api.paystack.co}
paystack.currency=${PAYSTACK_CURRENCY:GHS}

